obj-$(CONFIG_OMAP2_VRFB)	+= vrfb.o
obj-$(CONFIG_FB_OMAP2_DSS)	+= dss/
obj-$(CONFIG_FB_OMAP2)		+= omapfb.o
obj-y 						+= displays/
obj-y						+= dummy.o
omapfb-y := omapfb-main.o omapfb-sysfs.o omapfb-ioctl.o
