#
# Makefile for the IIO common modules.
# Common modules contains modules, which can be shared among multiple
# IIO modules. For example if the trigger processing is common for
# multiple IIO modules then this can be moved to a common module
# instead of duplicating in each module.
#

# When adding new entries keep the list in alphabetical order
obj-$(HID_SENSOR_IIO_COMMON)	+= hid-sensors/
obj-$(IIO_MS_SENSORS_I2C) 	+= ms_sensors/
obj-$(IIO_SSP_SENSORS_COMMONS)	+= ssp_sensors/
obj-$(IIO_ST_SENSORS_CORE)	+= st_sensors/
