obj-$(CONFIG_DVB_B2C2_FLEXCOP)	+= b2c2/
obj-$(CONFIG_VIDEO_SAA7146)	+= saa7146/
obj-$(CONFIG_SMS_SIANO_MDTV)	+= siano/
obj-$(CONFIG_VIDEO_V4L2_TPG)	+= v4l2-tpg/

obj-$(CONFIG_VIDEO_CX2341X) += cx2341x.o
obj-$(CONFIG_VIDEO_TVEEPROM) += tveeprom.o
obj-$(CONFIG_CYPRESS_FIRMWARE) += cypress_firmware.o
