#
# Makefile for the USB media device drivers
#

# DVB USB-only drivers
obj-$(CONFIG_DVB_TTUSB_DEC)			+= ttusb-dec/
obj-$(CONFIG_DVB_TTUSB_BUDGET)		+= ttusb-budget/
obj-$(CONFIG_DVB_USB)				+= dvb-usb/
obj-$(CONFIG_DVB_USB_V2)			+= dvb-usb-v2/
obj-$(CONFIG_SMS_USB_DRV)			+= siano/
obj-$(CONFIG_DVB_B2C2_FLEXCOP_USB)	+= b2c2/

obj-$(CONFIG_USB_ZR364XX)			+= zr364xx/
obj-$(CONFIG_USB_STKWEBCAM)			+= stkwebcam/
obj-$(CONFIG_USB_S2255)				+= s2255/

obj-$(CONFIG_USB_VIDEO_CLASS)		+= uvc/
obj-$(CONFIG_USB_GSPCA)         	+= gspca/
obj-$(CONFIG_USB_PWC)           	+= pwc/
obj-$(CONFIG_USB_AIRSPY)        	+= airspy/
obj-$(CONFIG_USB_HACKRF)        	+= hackrf/
obj-$(CONFIG_USB_MSI2500)       	+= msi2500/
obj-$(CONFIG_VIDEO_CPIA2)			+= cpia2/
obj-$(CONFIG_VIDEO_AU0828)			+= au0828/
obj-$(CONFIG_VIDEO_HDPVR)			+= hdpvr/
obj-$(CONFIG_VIDEO_PVRUSB2)			+= pvrusb2/
obj-$(CONFIG_VIDEO_USBVISION)		+= usbvision/
obj-$(CONFIG_VIDEO_STK1160)			+= stk1160/
obj-$(CONFIG_VIDEO_CX231XX)			+= cx231xx/
obj-$(CONFIG_VIDEO_TM6000)			+= tm6000/
obj-$(CONFIG_VIDEO_EM28XX)			+= em28xx/
obj-$(CONFIG_VIDEO_USBTV)			+= usbtv/
obj-$(CONFIG_VIDEO_GO7007)			+= go7007/
obj-$(CONFIG_DVB_AS102)				+= as102/
